repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.rs$'
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --force-scope]

  - repo: local
    hooks:
      - id: fix-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false

      - id: check-compilation
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

      - id: test-code
        name: cargo test
        entry: cargo test --all-targets
        language: system
        types: [rust]
        pass_filenames: false

      - id: check-docs
        name: "Check docs"
        entry: bash -c "cargo test --doc && cargo rustdoc -- -D warnings"
        language: system
        types: [rust]
        pass_filenames: false
